name: restaurant_management
description: "Restaurant management."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  badges: ^3.1.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter_animate: ^4.3.0
  hive: ^2.2.3
  lottie: ^2.7.0
  firebase_auth: ^4.16.0
  http: ^1.1.2
  get: ^4.6.6
  adaptive_theme: ^3.5.0
  google_nav_bar: ^5.0.6
  url_strategy: ^0.2.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/jsons/
    - assets/lotties/
    - assets/pictures/
